apiVersion: apps/v1
kind: Deployment
metadata:
  name: ms-java
spec:
  selector:
    matchLabels:
      app: ms-java
  template:
    metadata:
      labels:
        app: ms-java
    spec:
      containers:
        - name: ms-java
          image: lucascamilo2024/fit-strike-api:latest
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "prod"
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: aws-credentials
                  key: AWS_ACCESS_KEY_ID
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: aws-credentials
                  key: AWS_SECRET_ACCESS_KEY
            - name: AWS_REGION
              value: "us-east-1"