name: Deploy to AWS ECS

on:
    push:
        branches:
            - main

jobs:
    # Job to Build
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v3
            
            - name: Set Up JDK 21
              uses: actions/setup-java@v4
              with:
                java-version: '21'
                distribution: 'temurin'

            - name: Grant execute permission for gradlew
              run: chmod +x app/gradlew

            - name: Build with gradle
              run: ./gradlew bootBuildImage
              working-directory: app
    
    # Job Push to ECR
    push-ecr:
        runs-on: ubuntu-latest
        needs: build
        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Login to Amazon ECR
              id: login-ecr
              uses: aws-actions/amazon=ecr-login@v1

            - name: Build and Push Docker Image
              run: |
                IMAGE_TAG=latest
                IMAGE_URI=${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/${{ secrets.ECR_REPOSITORY_NAME }}:$IMAGE_TAG
                docker build -t $IMAGE_URI
                docker push $IMAGE_URI
              working-directory: app