name: Deploy to AWS ECS

on:
    push:
        branches:
            - main

jobs:
    # Job to Build
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v3
            
            - name: Set Up JDK 21
              uses: actions/setup-java@v4
              with:
                java-version: '21'
                distribution: 'graalvm'

            - name: Grant execute permission for gradlew
              run: chmod +x app/gradlew

            - name: Build with gradle
              run: ./gradlew nativeCompile
              working-directory: app
    
    # Job Push to ECR
    push-ecr:
        runs-on: ubuntu-latest
        needs: build
        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v2

            - name: Configure AWS CLI
              uses: aws-actions/configure-aws-credentials@v2
              with:
                aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
                aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                aws-region: ${{ secrets.AWS_REGION }}

            - name: Log in to Amazon ECR
              id: login-ecr
              uses: aws-actions/amazon-ecr-login@v1

            - name: Build, tag, and push Docker image
              env:
                ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
                ECR_REPOSITORY: secrets.ECR_REPOSITORY_NAME
                IMAGE_TAG: ${{ github.sha }}
              run: |
                # Build the Docker image with the specific tag (using the commit SHA)
                docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
                
                # Push the image with the specific tag
                docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
                
                # Tag the image as 'latest'
                docker tag $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG $ECR_REGISTRY/$ECR_REPOSITORY:latest
                
                # Push the 'latest' tag
                docker push $ECR_REGISTRY/$ECR_REPOSITORY:latest
              working-directory: app